### ISSUE TITLE
MEMBER_SIZE is too small

### ISSUE THREAD

**Issue by shavitush** [kidfearless/Stripper-Dump-Parser#1]
in the .inc, perhaps `MEMBER_SIZE` being set to 64 can be better
at the moment this will happen

![image](https://user-images.githubusercontent.com/3672466/61168921-294e0a80-a55e-11e9-8e56-b0313488317a.png)

![image](https://user-images.githubusercontent.com/3672466/61168922-2fdc8200-a55e-11e9-94b2-ac12477ce65a.png)

the output gets truncated to 32 characters, which is not enough. setting it to 64 fixes the issue

**Comment by RyamosThomas** [comment]
61eac831ff3ffdd6e524164ef651c94f5030b36f Fixes this.
