### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Lime18** [kidfearless/Stripper-Dump-Parser#2]
L 11/26/2019 - 22:35:47: [SM] MEMORY LEAK DETECTED IN PLUGIN (file "dump_parser.smx")
L 11/26/2019 - 22:35:47: [SM] Unloading plugin to free 28079 handles.
L 11/26/2019 - 22:35:47: [SM] Contact the author(s) of this plugin to correct this error.
L 11/26/2019 - 22:35:47: --------------------------------------------------------------------------
L 11/26/2019 - 22:35:47: Type	GlobalFwd           |	Count	2
L 11/26/2019 - 22:35:47: Type	Trie                |	Count	1
L 11/26/2019 - 22:35:47: Type	CellArray           |	Count	28076
L 11/26/2019 - 22:35:47: -- Approximately 461117844 bytes of memory are in use by (28079) Handles.

**Comment by RyamosThomas** [comment]
Do you have any plugins that use its natives? If so which natives? Does this happen on a certain map?

**Comment by Lime18** [comment]
use only for https://github.com/blankbhop/improved-showtriggers

**Comment by RyamosThomas** [comment]
Any particular map that this happens on?

**Comment by Lime18** [comment]
nope(

**Comment by RyamosThomas** [comment]
@Lime18 Try the changes in the latest commit, hopefully it will fix the memory leak. 
https://github.com/kidfearless/Stripper-Dump-Parser/blob/master/plugins/dump_parser.smx

**Comment by Lime18** [comment]
It looks like the problem is still not resolved :(

L 12/08/2019 - 17:04:47: [SM] MEMORY LEAK DETECTED IN PLUGIN (file "dump_parser.smx")
L 12/08/2019 - 17:04:47: [SM] Unloading plugin to free 25349 handles.
L 12/08/2019 - 17:04:47: [SM] Contact the author(s) of this plugin to correct this error.
L 12/08/2019 - 17:04:47: --------------------------------------------------------------------------
L 12/08/2019 - 17:04:47: Type	GlobalFwd           |	Count	2
L 12/08/2019 - 17:04:47: Type	Trie                |	Count	1
L 12/08/2019 - 17:04:47: Type	CellArray           |	Count	25346
L 12/08/2019 - 17:04:47: -- Approximately 413530572 bytes of memory are in use by (25349) Handles.

**Comment by Lime18** [comment]
L 12/10/2019 - 18:28:24: [SM] Exception reported: Memory leak
L 12/10/2019 - 18:28:24: [SM] Blaming: dump_parser.smx
L 12/10/2019 - 18:28:24: [SM] Call stack trace:
L 12/10/2019 - 18:28:24: [SM]   [0] ArrayList.Clone
L 12/10/2019 - 18:28:24: [SM]   [1] Line 134, C:\Users\pe\Documents\GitHub\Stripper-Dump-Parser\scripting\include\dump_parser.inc::CloneEntity
L 12/10/2019 - 18:28:24: [SM]   [2] Line 578, C:\Users\pe\Documents\GitHub\Stripper-Dump-Parser\scripting\dump_parser.sp::Native_GetDumpEntityAsArray
L 12/10/2019 - 18:28:24: [SM]   [4] GetDumpEntityAsArray
L 12/10/2019 - 18:28:24: [SM]   [5] Line 191, E:\Сервера\CSGO 2015.08\scripting 1.10 (6377) Bhop 1-3\include\dump_parser.inc::GetDumpEntity
L 12/10/2019 - 18:28:24: [SM]   [6] Line 272, E:\Сервера\CSGO 2015.08\scripting 1.10 (6377) Bhop 1-3\include\dump_parser.inc::GetOutputCount
L 12/10/2019 - 18:28:24: [SM]   [7] Line 78, E:\Сервера\CSGO 2015.08\scripting 1.10 (6377) Bhop 1-3\improved-st.sp::OnRoundStart
L 12/10/2019 - 18:28:24: [SM] MEMORY LEAK DETECTED IN PLUGIN (file "dump_parser.smx")
L 12/10/2019 - 18:28:24: [SM] Unloading plugin to free 28865 handles.
L 12/10/2019 - 18:28:24: [SM] Contact the author(s) of this plugin to correct this error.
L 12/10/2019 - 18:28:24: --------------------------------------------------------------------------
L 12/10/2019 - 18:28:24: Type	GlobalFwd           |	Count	2
L 12/10/2019 - 18:28:24: Type	Trie                |	Count	1
L 12/10/2019 - 18:28:24: Type	CellArray           |	Count	28862
L 12/10/2019 - 18:28:24: -- Approximately 473584700 bytes of memory are in use by (28865) Handles.

**Comment by RyamosThomas** [comment]
It looks like you might not have updated the include file. What I would recommend is downloading the latest version of improved show triggers here and compiling it. https://github.com/blankbhop/improved-showtriggers
You don't need to change any includes with the v2 release as it comes with the outputinfo natives. https://github.com/kidfearless/output-info-plugin/releases

v2 doesn't have late loading so it may take a map change for it to work.
